// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: amenities.sql

package sqlc

import (
	"context"
)

const addAmenityToHotel = `-- name: AddAmenityToHotel :one
INSERT INTO hotel_amenities (hotel_id, amenity_id)
VALUES ($1, $2)
RETURNING hotel_id, amenity_id
`

type AddAmenityToHotelParams struct {
	HotelID   int64 `json:"hotel_id"`
	AmenityID int64 `json:"amenity_id"`
}

func (q *Queries) AddAmenityToHotel(ctx context.Context, arg AddAmenityToHotelParams) (HotelAmenity, error) {
	row := q.db.QueryRow(ctx, addAmenityToHotel, arg.HotelID, arg.AmenityID)
	var i HotelAmenity
	err := row.Scan(&i.HotelID, &i.AmenityID)
	return i, err
}

const createAmenity = `-- name: CreateAmenity :one
INSERT INTO amenities (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateAmenity(ctx context.Context, name string) (Amenity, error) {
	row := q.db.QueryRow(ctx, createAmenity, name)
	var i Amenity
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listAmenities = `-- name: ListAmenities :many
SELECT id, name, created_at
FROM amenities
ORDER BY name
`

func (q *Queries) ListAmenities(ctx context.Context) ([]Amenity, error) {
	rows, err := q.db.Query(ctx, listAmenities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amenity
	for rows.Next() {
		var i Amenity
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAmenitiesByHotel = `-- name: ListAmenitiesByHotel :many
SELECT
    a.id,
    a.name,
    a.created_at
FROM amenities AS a
JOIN hotel_amenities AS ha
    ON ha.amenity_id = a.id
WHERE ha.hotel_id = $1
ORDER BY a.name
`

func (q *Queries) ListAmenitiesByHotel(ctx context.Context, hotelID int64) ([]Amenity, error) {
	rows, err := q.db.Query(ctx, listAmenitiesByHotel, hotelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Amenity
	for rows.Next() {
		var i Amenity
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAmenityFromHotel = `-- name: RemoveAmenityFromHotel :one
DELETE FROM hotel_amenities
WHERE hotel_id = $1
  AND amenity_id = $2
RETURNING amenity_id
`

type RemoveAmenityFromHotelParams struct {
	HotelID   int64 `json:"hotel_id"`
	AmenityID int64 `json:"amenity_id"`
}

func (q *Queries) RemoveAmenityFromHotel(ctx context.Context, arg RemoveAmenityFromHotelParams) (int64, error) {
	row := q.db.QueryRow(ctx, removeAmenityFromHotel, arg.HotelID, arg.AmenityID)
	var amenity_id int64
	err := row.Scan(&amenity_id)
	return amenity_id, err
}
