// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT
    id,
    email,
    full_name,
    phone,
    password_hash,
    role,
    created_at,
    updated_at
FROM users
WHERE lower(email) = lower($1)
`

type GetUserForLoginRow struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
	Phone        pgtype.Text        `json:"phone"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, lower string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, lower)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerUser = `-- name: RegisterUser :one
INSERT INTO users (
    email,
    full_name,
    phone,
    password_hash
)
VALUES ($1, $2, $3, $4)
RETURNING
    id,
    email,
    full_name,
    phone,
    role,
    created_at,
    updated_at
`

type RegisterUserParams struct {
	Email        string      `json:"email"`
	FullName     string      `json:"full_name"`
	Phone        pgtype.Text `json:"phone"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

type RegisterUserRow struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	Phone     pgtype.Text        `json:"phone"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (RegisterUserRow, error) {
	row := q.db.QueryRow(ctx, registerUser,
		arg.Email,
		arg.FullName,
		arg.Phone,
		arg.PasswordHash,
	)
	var i RegisterUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
