// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    user_id,
    room_type_id,
    check_in,
    check_out,
    rooms_count,
    guest_count,
    price_per_night,
    total_price
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $7::numeric
        * ($4::date - $3::date)
        * $5::int
)
RETURNING
    id,
    user_id,
    room_type_id,
    check_in,
    check_out,
    rooms_count,
    guest_count,
    price_per_night,
    total_price,
    status,
    created_at,
    updated_at
`

type CreateBookingParams struct {
	UserID        int64          `json:"user_id"`
	RoomTypeID    int64          `json:"room_type_id"`
	CheckIn       pgtype.Date    `json:"check_in"`
	CheckOut      pgtype.Date    `json:"check_out"`
	RoomsCount    int32          `json:"rooms_count"`
	GuestCount    int32          `json:"guest_count"`
	PricePerNight pgtype.Numeric `json:"price_per_night"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.UserID,
		arg.RoomTypeID,
		arg.CheckIn,
		arg.CheckOut,
		arg.RoomsCount,
		arg.GuestCount,
		arg.PricePerNight,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomTypeID,
		&i.CheckIn,
		&i.CheckOut,
		&i.RoomsCount,
		&i.GuestCount,
		&i.PricePerNight,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureAvailabilityRows = `-- name: EnsureAvailabilityRows :exec
INSERT INTO room_type_availability (
    room_type_id,
    date,
    rooms_booked
)
SELECT
    $1::bigint,
    $2::date + offsets.day_offset,
    0
FROM generate_series(
    0,
    ($3::date - $2::date) - 1
) AS offsets(day_offset)
ON CONFLICT (room_type_id, date) DO NOTHING
`

type EnsureAvailabilityRowsParams struct {
	RoomTypeID int64       `json:"room_type_id"`
	CheckIn    pgtype.Date `json:"check_in"`
	CheckOut   pgtype.Date `json:"check_out"`
}

func (q *Queries) EnsureAvailabilityRows(ctx context.Context, arg EnsureAvailabilityRowsParams) error {
	_, err := q.db.Exec(ctx, ensureAvailabilityRows, arg.RoomTypeID, arg.CheckIn, arg.CheckOut)
	return err
}

const getBookingByIDForUser = `-- name: GetBookingByIDForUser :one
SELECT
    id,
    user_id,
    room_type_id,
    check_in,
    check_out,
    rooms_count,
    guest_count,
    price_per_night,
    total_price,
    status,
    created_at,
    updated_at
FROM bookings
WHERE id = $1
AND user_id = $2
`

type GetBookingByIDForUserParams struct {
	BookingID int64 `json:"booking_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetBookingByIDForUser(ctx context.Context, arg GetBookingByIDForUserParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByIDForUser, arg.BookingID, arg.UserID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomTypeID,
		&i.CheckIn,
		&i.CheckOut,
		&i.RoomsCount,
		&i.GuestCount,
		&i.PricePerNight,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomTypeForBooking = `-- name: GetRoomTypeForBooking :one
SELECT
    id,
    price_per_night,
    capacity,
    total_rooms
FROM room_types
WHERE id = $1
FOR SHARE
`

type GetRoomTypeForBookingRow struct {
	ID            int64          `json:"id"`
	PricePerNight pgtype.Numeric `json:"price_per_night"`
	Capacity      int32          `json:"capacity"`
	TotalRooms    int32          `json:"total_rooms"`
}

func (q *Queries) GetRoomTypeForBooking(ctx context.Context, roomTypeID int64) (GetRoomTypeForBookingRow, error) {
	row := q.db.QueryRow(ctx, getRoomTypeForBooking, roomTypeID)
	var i GetRoomTypeForBookingRow
	err := row.Scan(
		&i.ID,
		&i.PricePerNight,
		&i.Capacity,
		&i.TotalRooms,
	)
	return i, err
}

const incrementAvailability = `-- name: IncrementAvailability :execrows
UPDATE room_type_availability
SET rooms_booked = rooms_booked + $1::int
WHERE room_type_id = $2
  AND date >= $3::date
  AND date < $4::date
  AND rooms_booked + $1::int
      <= $5::int
`

type IncrementAvailabilityParams struct {
	RoomsCount int32       `json:"rooms_count"`
	RoomTypeID int64       `json:"room_type_id"`
	CheckIn    pgtype.Date `json:"check_in"`
	CheckOut   pgtype.Date `json:"check_out"`
	TotalRooms int32       `json:"total_rooms"`
}

func (q *Queries) IncrementAvailability(ctx context.Context, arg IncrementAvailabilityParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementAvailability,
		arg.RoomsCount,
		arg.RoomTypeID,
		arg.CheckIn,
		arg.CheckOut,
		arg.TotalRooms,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT
    id,
    user_id,
    room_type_id,
    check_in,
    check_out,
    rooms_count,
    guest_count,
    price_per_night,
    total_price,
    status,
    created_at,
    updated_at
FROM bookings
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListBookingsByUser(ctx context.Context, userID int64) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoomTypeID,
			&i.CheckIn,
			&i.CheckOut,
			&i.RoomsCount,
			&i.GuestCount,
			&i.PricePerNight,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAvailabilityRows = `-- name: LockAvailabilityRows :many
SELECT
    date,
    rooms_booked
FROM room_type_availability
WHERE room_type_id = $1
  AND date >= $2::date
  AND date < $3::date
ORDER BY date
FOR UPDATE
`

type LockAvailabilityRowsParams struct {
	RoomTypeID int64       `json:"room_type_id"`
	CheckIn    pgtype.Date `json:"check_in"`
	CheckOut   pgtype.Date `json:"check_out"`
}

type LockAvailabilityRowsRow struct {
	Date        pgtype.Date `json:"date"`
	RoomsBooked int32       `json:"rooms_booked"`
}

func (q *Queries) LockAvailabilityRows(ctx context.Context, arg LockAvailabilityRowsParams) ([]LockAvailabilityRowsRow, error) {
	rows, err := q.db.Query(ctx, lockAvailabilityRows, arg.RoomTypeID, arg.CheckIn, arg.CheckOut)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockAvailabilityRowsRow
	for rows.Next() {
		var i LockAvailabilityRowsRow
		if err := rows.Scan(&i.Date, &i.RoomsBooked); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
