// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hotels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHotel = `-- name: CreateHotel :one
INSERT INTO hotels (name, address, city, description)
VALUES ($1, $2, $3, $4)
RETURNING id, name, address, city, description, created_at
`

type CreateHotelParams struct {
	Name        string      `json:"name"`
	Address     string      `json:"address"`
	City        string      `json:"city"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateHotel(ctx context.Context, arg CreateHotelParams) (Hotel, error) {
	row := q.db.QueryRow(ctx, createHotel,
		arg.Name,
		arg.Address,
		arg.City,
		arg.Description,
	)
	var i Hotel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHotel = `-- name: DeleteHotel :one
DELETE FROM hotels
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteHotel(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteHotel, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getHotelByID = `-- name: GetHotelByID :one
SELECT id, name, address, city, description, created_at FROM hotels
WHERE id = $1
`

func (q *Queries) GetHotelByID(ctx context.Context, id int64) (Hotel, error) {
	row := q.db.QueryRow(ctx, getHotelByID, id)
	var i Hotel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listHotelsByCity = `-- name: ListHotelsByCity :many
SELECT id, name, address, city, description, created_at FROM hotels
WHERE city = $1
ORDER BY name
`

func (q *Queries) ListHotelsByCity(ctx context.Context, city string) ([]Hotel, error) {
	rows, err := q.db.Query(ctx, listHotelsByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hotel
	for rows.Next() {
		var i Hotel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAvailableHotels = `-- name: SearchAvailableHotels :many
WITH available_room_types AS (
    SELECT
        rt.id,
        rt.hotel_id,
        rt.price_per_night
    FROM room_types AS rt
    LEFT JOIN room_type_availability AS rta
        ON rta.room_type_id = rt.id
       AND rta.date >= $4::date
       AND rta.date < $5::date
    GROUP BY rt.id
    HAVING
    rt.total_rooms
        - COALESCE(MAX(rta.rooms_booked + rta.rooms_blocked), 0)
        >= $6::int
    AND rt.capacity * $6::int
        >= $7::int
),
matching_hotels AS (
    SELECT
        h.id,
        h.name,
        h.address,
        h.city,
        h.description,
        h.created_at,
        hi.image_url AS primary_image_url,
        MIN(art.price_per_night)::numeric(10,2) AS starting_price,
        COUNT(art.id)::int AS available_room_type_count
    FROM hotels AS h
    JOIN available_room_types AS art
        ON art.hotel_id = h.id
    LEFT JOIN hotel_images AS hi
        ON hi.hotel_id = h.id
       AND hi.is_primary = true
    WHERE lower(h.city) = lower($8)
    GROUP BY
        h.id,
        hi.image_url
)
SELECT id, name, address, city, description, created_at, primary_image_url, starting_price, available_room_type_count
FROM matching_hotels
ORDER BY
    CASE
        WHEN $1::text = 'price_asc' THEN starting_price
    END ASC,
    CASE
        WHEN $1::text = 'price_desc' THEN starting_price
    END DESC,
    id ASC
LIMIT $3::bigint
OFFSET $2::bigint
`

type SearchAvailableHotelsParams struct {
	Sort         string      `json:"sort"`
	ResultOffset int64       `json:"result_offset"`
	ResultLimit  int64       `json:"result_limit"`
	CheckIn      pgtype.Date `json:"check_in"`
	CheckOut     pgtype.Date `json:"check_out"`
	RoomsCount   int32       `json:"rooms_count"`
	GuestCount   int32       `json:"guest_count"`
	City         string      `json:"city"`
}

type SearchAvailableHotelsRow struct {
	ID                     int64              `json:"id"`
	Name                   string             `json:"name"`
	Address                string             `json:"address"`
	City                   string             `json:"city"`
	Description            pgtype.Text        `json:"description"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	PrimaryImageUrl        pgtype.Text        `json:"primary_image_url"`
	StartingPrice          pgtype.Numeric     `json:"starting_price"`
	AvailableRoomTypeCount int32              `json:"available_room_type_count"`
}

func (q *Queries) SearchAvailableHotels(ctx context.Context, arg SearchAvailableHotelsParams) ([]SearchAvailableHotelsRow, error) {
	rows, err := q.db.Query(ctx, searchAvailableHotels,
		arg.Sort,
		arg.ResultOffset,
		arg.ResultLimit,
		arg.CheckIn,
		arg.CheckOut,
		arg.RoomsCount,
		arg.GuestCount,
		arg.City,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAvailableHotelsRow
	for rows.Next() {
		var i SearchAvailableHotelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.Description,
			&i.CreatedAt,
			&i.PrimaryImageUrl,
			&i.StartingPrice,
			&i.AvailableRoomTypeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHotel = `-- name: UpdateHotel :one
UPDATE hotels
SET
    name = $2,
    address = $3,
    city = $4,
    description = $5
WHERE id = $1
RETURNING id, name, address, city, description, created_at
`

type UpdateHotelParams struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Address     string      `json:"address"`
	City        string      `json:"city"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateHotel(ctx context.Context, arg UpdateHotelParams) (Hotel, error) {
	row := q.db.QueryRow(ctx, updateHotel,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.Description,
	)
	var i Hotel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
