// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hotels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHotel = `-- name: CreateHotel :one
INSERT INTO hotels (name, address, city, description)
VALUES ($1, $2, $3, $4)
RETURNING id, name, address, city, description, created_at
`

type CreateHotelParams struct {
	Name        string      `json:"name"`
	Address     string      `json:"address"`
	City        string      `json:"city"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateHotel(ctx context.Context, arg CreateHotelParams) (Hotel, error) {
	row := q.db.QueryRow(ctx, createHotel,
		arg.Name,
		arg.Address,
		arg.City,
		arg.Description,
	)
	var i Hotel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getHotelByID = `-- name: GetHotelByID :one
SELECT id, name, address, city, description, created_at FROM hotels
WHERE id = $1
`

func (q *Queries) GetHotelByID(ctx context.Context, id int64) (Hotel, error) {
	row := q.db.QueryRow(ctx, getHotelByID, id)
	var i Hotel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listHotelsByCity = `-- name: ListHotelsByCity :many
SELECT id, name, address, city, description, created_at FROM hotels
WHERE city = $1
ORDER BY name
`

func (q *Queries) ListHotelsByCity(ctx context.Context, city string) ([]Hotel, error) {
	rows, err := q.db.Query(ctx, listHotelsByCity, city)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hotel
	for rows.Next() {
		var i Hotel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
