// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hotels_images.sql

package sqlc

import (
	"context"
)

const clearPrimaryHotelImage = `-- name: ClearPrimaryHotelImage :exec
UPDATE hotel_images
SET is_primary = false
WHERE hotel_id = $1
  AND is_primary = true
`

func (q *Queries) ClearPrimaryHotelImage(ctx context.Context, hotelID int64) error {
	_, err := q.db.Exec(ctx, clearPrimaryHotelImage, hotelID)
	return err
}

const createHotelImage = `-- name: CreateHotelImage :one
WITH active_hotel AS (
    SELECT h.id
    FROM hotels AS h
    WHERE h.id = $2
      AND h.is_active = true
    FOR SHARE OF h
)
INSERT INTO hotel_images (
    hotel_id,
    image_url
)
SELECT
    active_hotel.id,
    $1::text
FROM active_hotel
RETURNING id, hotel_id, image_url, is_primary, created_at
`

type CreateHotelImageParams struct {
	ImageUrl string `json:"image_url"`
	HotelID  int64  `json:"hotel_id"`
}

func (q *Queries) CreateHotelImage(ctx context.Context, arg CreateHotelImageParams) (HotelImage, error) {
	row := q.db.QueryRow(ctx, createHotelImage, arg.ImageUrl, arg.HotelID)
	var i HotelImage
	err := row.Scan(
		&i.ID,
		&i.HotelID,
		&i.ImageUrl,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHotelImage = `-- name: DeleteHotelImage :one
WITH active_hotel AS (
    SELECT h.id
    FROM hotels AS h
    WHERE h.id = $2
      AND h.is_active = true
    FOR SHARE OF h
)
DELETE FROM hotel_images AS hi
USING active_hotel
WHERE hi.id = $1
  AND hi.hotel_id = active_hotel.id
RETURNING hi.id
`

type DeleteHotelImageParams struct {
	ImageID int64 `json:"image_id"`
	HotelID int64 `json:"hotel_id"`
}

func (q *Queries) DeleteHotelImage(ctx context.Context, arg DeleteHotelImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteHotelImage, arg.ImageID, arg.HotelID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listHotelImages = `-- name: ListHotelImages :many
SELECT hi.id, hi.hotel_id, hi.image_url, hi.is_primary, hi.created_at
FROM hotel_images AS hi
JOIN hotels AS h
    ON h.id = hi.hotel_id
WHERE hi.hotel_id = $1
  AND h.is_active = true
ORDER BY
    hi.is_primary DESC,
    hi.created_at ASC,
    hi.id ASC
`

func (q *Queries) ListHotelImages(ctx context.Context, hotelID int64) ([]HotelImage, error) {
	rows, err := q.db.Query(ctx, listHotelImages, hotelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HotelImage
	for rows.Next() {
		var i HotelImage
		if err := rows.Scan(
			&i.ID,
			&i.HotelID,
			&i.ImageUrl,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHotelForImageUpdate = `-- name: LockHotelForImageUpdate :one
SELECT id
FROM hotels
WHERE id = $1
  AND is_active = true
FOR UPDATE
`

func (q *Queries) LockHotelForImageUpdate(ctx context.Context, hotelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockHotelForImageUpdate, hotelID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setPrimaryHotelImage = `-- name: SetPrimaryHotelImage :one
UPDATE hotel_images
SET is_primary = true
WHERE id = $1
  AND hotel_id = $2
RETURNING id, hotel_id, image_url, is_primary, created_at
`

type SetPrimaryHotelImageParams struct {
	ImageID int64 `json:"image_id"`
	HotelID int64 `json:"hotel_id"`
}

func (q *Queries) SetPrimaryHotelImage(ctx context.Context, arg SetPrimaryHotelImageParams) (HotelImage, error) {
	row := q.db.QueryRow(ctx, setPrimaryHotelImage, arg.ImageID, arg.HotelID)
	var i HotelImage
	err := row.Scan(
		&i.ID,
		&i.HotelID,
		&i.ImageUrl,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}
