// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRoomTypeInventory = `-- name: ListRoomTypeInventory :many
WITH requested_dates AS (
    SELECT generate_series(
        $2::date,
        $3::date - 1,
        interval '1 day'
    )::date AS date
)
SELECT
    requested_dates.date,
    rt.total_rooms,
    COALESCE(rta.rooms_booked, 0)::int AS rooms_booked,
    COALESCE(rta.rooms_blocked, 0)::int AS rooms_blocked,
    rta.block_reason,
    (
        rt.total_rooms
        - COALESCE(rta.rooms_booked, 0)
        - COALESCE(rta.rooms_blocked, 0)
    )::int AS rooms_available
FROM room_types AS rt
CROSS JOIN requested_dates
LEFT JOIN room_type_availability AS rta
    ON rta.room_type_id = rt.id
   AND rta.date = requested_dates.date
WHERE rt.id = $1
ORDER BY requested_dates.date
`

type ListRoomTypeInventoryParams struct {
	RoomTypeID int64       `json:"room_type_id"`
	DateFrom   pgtype.Date `json:"date_from"`
	DateTo     pgtype.Date `json:"date_to"`
}

type ListRoomTypeInventoryRow struct {
	Date           pgtype.Date `json:"date"`
	TotalRooms     int32       `json:"total_rooms"`
	RoomsBooked    int32       `json:"rooms_booked"`
	RoomsBlocked   int32       `json:"rooms_blocked"`
	BlockReason    pgtype.Text `json:"block_reason"`
	RoomsAvailable int32       `json:"rooms_available"`
}

func (q *Queries) ListRoomTypeInventory(ctx context.Context, arg ListRoomTypeInventoryParams) ([]ListRoomTypeInventoryRow, error) {
	rows, err := q.db.Query(ctx, listRoomTypeInventory, arg.RoomTypeID, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomTypeInventoryRow
	for rows.Next() {
		var i ListRoomTypeInventoryRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalRooms,
			&i.RoomsBooked,
			&i.RoomsBlocked,
			&i.BlockReason,
			&i.RoomsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBlockedInventory = `-- name: SetBlockedInventory :execrows
UPDATE room_type_availability
SET
    rooms_blocked = $1::int,
    block_reason = CASE
        WHEN $1::int = 0 THEN NULL
        ELSE btrim($2::text)
    END
WHERE room_type_id = $3
  AND date >= $4::date
  AND date < $5::date
  AND rooms_booked + $1::int
      <= $6::int
`

type SetBlockedInventoryParams struct {
	RoomsBlocked int32       `json:"rooms_blocked"`
	BlockReason  string      `json:"block_reason"`
	RoomTypeID   int64       `json:"room_type_id"`
	DateFrom     pgtype.Date `json:"date_from"`
	DateTo       pgtype.Date `json:"date_to"`
	TotalRooms   int32       `json:"total_rooms"`
}

func (q *Queries) SetBlockedInventory(ctx context.Context, arg SetBlockedInventoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBlockedInventory,
		arg.RoomsBlocked,
		arg.BlockReason,
		arg.RoomTypeID,
		arg.DateFrom,
		arg.DateTo,
		arg.TotalRooms,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
