// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Amenity struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Hotel struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Address     string             `json:"address"`
	City        string             `json:"city"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type HotelAmenity struct {
	HotelID   int64 `json:"hotel_id"`
	AmenityID int64 `json:"amenity_id"`
}

type RoomType struct {
	ID            int64              `json:"id"`
	HotelID       int64              `json:"hotel_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	PricePerNight pgtype.Numeric     `json:"price_per_night"`
	Capacity      int32              `json:"capacity"`
	TotalRooms    int32              `json:"total_rooms"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Role         string             `json:"role"`
	FullName     string             `json:"full_name"`
	Phone        pgtype.Text        `json:"phone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
