// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Amenity struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Booking struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	RoomTypeID    int64              `json:"room_type_id"`
	CheckIn       pgtype.Date        `json:"check_in"`
	CheckOut      pgtype.Date        `json:"check_out"`
	RoomsCount    int32              `json:"rooms_count"`
	GuestCount    int32              `json:"guest_count"`
	PricePerNight pgtype.Numeric     `json:"price_per_night"`
	TotalPrice    pgtype.Numeric     `json:"total_price"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type BookingIdempotencyKey struct {
	UserID         int64              `json:"user_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    []byte             `json:"request_hash"`
	BookingID      pgtype.Int8        `json:"booking_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type BookingStatusHistory struct {
	ID              int64              `json:"id"`
	BookingID       int64              `json:"booking_id"`
	FromStatus      pgtype.Text        `json:"from_status"`
	ToStatus        string             `json:"to_status"`
	ChangedByUserID pgtype.Int8        `json:"changed_by_user_id"`
	Reason          pgtype.Text        `json:"reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Hotel struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Address     string             `json:"address"`
	City        string             `json:"city"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type HotelAmenity struct {
	HotelID   int64 `json:"hotel_id"`
	AmenityID int64 `json:"amenity_id"`
}

type HotelImage struct {
	ID        int64              `json:"id"`
	HotelID   int64              `json:"hotel_id"`
	ImageUrl  string             `json:"image_url"`
	IsPrimary bool               `json:"is_primary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OauthAccount struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	ProviderEmail  string             `json:"provider_email"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PasswordResetRequest struct {
	ID                  int64              `json:"id"`
	UserID              int64              `json:"user_id"`
	OtpHash             []byte             `json:"otp_hash"`
	Attempts            int16              `json:"attempts"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	VerifiedAt          pgtype.Timestamptz `json:"verified_at"`
	ResetTokenHash      []byte             `json:"reset_token_hash"`
	ResetTokenExpiresAt pgtype.Timestamptz `json:"reset_token_expires_at"`
	ConsumedAt          pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	TokenHash         []byte             `json:"token_hash"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByTokenID pgtype.Int8        `json:"replaced_by_token_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Review struct {
	ID        int64              `json:"id"`
	BookingID int64              `json:"booking_id"`
	Rating    int16              `json:"rating"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	EditedAt  pgtype.Timestamptz `json:"edited_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type RoomType struct {
	ID            int64              `json:"id"`
	HotelID       int64              `json:"hotel_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	PricePerNight pgtype.Numeric     `json:"price_per_night"`
	Capacity      int32              `json:"capacity"`
	TotalRooms    int32              `json:"total_rooms"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RoomTypeAvailability struct {
	RoomTypeID   int64       `json:"room_type_id"`
	Date         pgtype.Date `json:"date"`
	RoomsBooked  int32       `json:"rooms_booked"`
	RoomsBlocked int32       `json:"rooms_blocked"`
	BlockReason  pgtype.Text `json:"block_reason"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Role         string             `json:"role"`
	FullName     string             `json:"full_name"`
	Phone        pgtype.Text        `json:"phone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
