// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (
    user_id,
    provider,
    provider_user_id,
    provider_email
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    user_id,
    provider,
    provider_user_id,
    provider_email,
    created_at,
    updated_at
`

type CreateOAuthAccountParams struct {
	UserID         int64  `json:"user_id"`
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
	ProviderEmail  string `json:"provider_email"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderEmail,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccountForUpdate = `-- name: GetOAuthAccountForUpdate :one
SELECT
    id,
    user_id,
    provider,
    provider_user_id,
    provider_email,
    created_at,
    updated_at
FROM oauth_accounts
WHERE provider = $1
  AND provider_user_id = $2
FOR UPDATE
`

type GetOAuthAccountForUpdateParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

// Rechecked inside the account-linking transaction.
// Lock the OAuth account before changing its stored provider email.
func (q *Queries) GetOAuthAccountForUpdate(ctx context.Context, arg GetOAuthAccountForUpdateParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountForUpdate, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthUserByProviderSubject = `-- name: GetOAuthUserByProviderSubject :one
SELECT
    oa.id AS oauth_account_id,
    oa.user_id,
    oa.provider,
    oa.provider_user_id,
    oa.provider_email,
    u.email,
    u.full_name,
    u.role
FROM oauth_accounts AS oa
JOIN users AS u
    ON u.id = oa.user_id
WHERE oa.provider = $1
  AND oa.provider_user_id = $2
`

type GetOAuthUserByProviderSubjectParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

type GetOAuthUserByProviderSubjectRow struct {
	OauthAccountID int64  `json:"oauth_account_id"`
	UserID         int64  `json:"user_id"`
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
	ProviderEmail  string `json:"provider_email"`
	Email          string `json:"email"`
	FullName       string `json:"full_name"`
	Role           string `json:"role"`
}

// Used for normal OAuth login after the identity has already been linked.
func (q *Queries) GetOAuthUserByProviderSubject(ctx context.Context, arg GetOAuthUserByProviderSubjectParams) (GetOAuthUserByProviderSubjectRow, error) {
	row := q.db.QueryRow(ctx, getOAuthUserByProviderSubject, arg.Provider, arg.ProviderUserID)
	var i GetOAuthUserByProviderSubjectRow
	err := row.Scan(
		&i.OauthAccountID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.Email,
		&i.FullName,
		&i.Role,
	)
	return i, err
}

const getOrCreateOAuthUser = `-- name: GetOrCreateOAuthUser :one
INSERT INTO users (
    email,
    full_name
)
VALUES (
    $1,
    $2
)
ON CONFLICT (lower(email))
DO UPDATE SET
    email = users.email
RETURNING
    id,
    email,
    full_name,
    role,
    created_at,
    updated_at
`

type GetOrCreateOAuthUserParams struct {
	Email    string `json:"email"`
	FullName string `json:"full_name"`
}

type GetOrCreateOAuthUserRow struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Creates a passwordless customer when the email is new.
// If the verified Google email already belongs to a Ryoko user, this performs
// a no-op update and returns that existing user while locking its row.
//
// The conflict target matches users_email_unique_ci.
func (q *Queries) GetOrCreateOAuthUser(ctx context.Context, arg GetOrCreateOAuthUserParams) (GetOrCreateOAuthUserRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateOAuthUser, arg.Email, arg.FullName)
	var i GetOrCreateOAuthUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOAuthAccountEmail = `-- name: UpdateOAuthAccountEmail :one
UPDATE oauth_accounts
SET
    provider_email = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING
    id,
    user_id,
    provider,
    provider_user_id,
    provider_email,
    created_at,
    updated_at
`

type UpdateOAuthAccountEmailParams struct {
	ProviderEmail  string `json:"provider_email"`
	OauthAccountID int64  `json:"oauth_account_id"`
}

// Keep the provider-email snapshot current when Google reports a changed
// verified email. This does not automatically change users.email.
func (q *Queries) UpdateOAuthAccountEmail(ctx context.Context, arg UpdateOAuthAccountEmailParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, updateOAuthAccountEmail, arg.ProviderEmail, arg.OauthAccountID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
