// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_login_codes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOAuthLoginCode = `-- name: ConsumeOAuthLoginCode :one
UPDATE oauth_login_codes
SET consumed_at = $1
WHERE id = $2
  AND consumed_at IS NULL
RETURNING id
`

type ConsumeOAuthLoginCodeParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ID         int64              `json:"id"`
}

func (q *Queries) ConsumeOAuthLoginCode(ctx context.Context, arg ConsumeOAuthLoginCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, consumeOAuthLoginCode, arg.ConsumedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOAuthLoginCode = `-- name: CreateOAuthLoginCode :one
INSERT INTO oauth_login_codes (
    user_id,
    code_hash,
    expires_at
)
VALUES ($1, $2, $3)
RETURNING id, user_id, code_hash, expires_at, consumed_at, created_at
`

type CreateOAuthLoginCodeParams struct {
	UserID    int64              `json:"user_id"`
	CodeHash  []byte             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuthLoginCode(ctx context.Context, arg CreateOAuthLoginCodeParams) (OauthLoginCode, error) {
	row := q.db.QueryRow(ctx, createOAuthLoginCode, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	var i OauthLoginCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOAuthLoginCodes = `-- name: DeleteExpiredOAuthLoginCodes :execrows
DELETE FROM oauth_login_codes
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredOAuthLoginCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOAuthLoginCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOAuthLoginCodeForUpdate = `-- name: GetOAuthLoginCodeForUpdate :one
SELECT
    olc.id,
    olc.user_id,
    olc.expires_at,
    olc.consumed_at,
    u.role
FROM oauth_login_codes AS olc
JOIN users AS u ON u.id = olc.user_id
WHERE olc.code_hash = $1
FOR UPDATE OF olc
`

type GetOAuthLoginCodeForUpdateRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	Role       string             `json:"role"`
}

func (q *Queries) GetOAuthLoginCodeForUpdate(ctx context.Context, codeHash []byte) (GetOAuthLoginCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOAuthLoginCodeForUpdate, codeHash)
	var i GetOAuthLoginCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Role,
	)
	return i, err
}
