// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeActivePasswordResetRequests = `-- name: ConsumeActivePasswordResetRequests :execrows
UPDATE password_reset_requests
SET consumed_at = $1
WHERE user_id = $2
  AND consumed_at IS NULL
`

type ConsumeActivePasswordResetRequestsParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	UserID     int64              `json:"user_id"`
}

// Invalidates any previous OTP or verified reset token.
func (q *Queries) ConsumeActivePasswordResetRequests(ctx context.Context, arg ConsumeActivePasswordResetRequestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeActivePasswordResetRequests, arg.ConsumedAt, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumePasswordResetRequest = `-- name: ConsumePasswordResetRequest :one
UPDATE password_reset_requests
SET consumed_at = $1
WHERE id = $2
  AND consumed_at IS NULL
  AND verified_at IS NOT NULL
  AND reset_token_expires_at > $1
RETURNING user_id
`

type ConsumePasswordResetRequestParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ID         int64              `json:"id"`
}

// Call after updating the password and revoking refresh sessions,
// within the same transaction.
func (q *Queries) ConsumePasswordResetRequest(ctx context.Context, arg ConsumePasswordResetRequestParams) (int64, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetRequest, arg.ConsumedAt, arg.ID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createPasswordResetRequest = `-- name: CreatePasswordResetRequest :one
INSERT INTO password_reset_requests (
    user_id,
    otp_hash,
    expires_at
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    user_id,
    otp_hash,
    attempts,
    expires_at,
    verified_at,
    reset_token_hash,
    reset_token_expires_at,
    consumed_at,
    created_at
`

type CreatePasswordResetRequestParams struct {
	UserID    int64              `json:"user_id"`
	OtpHash   []byte             `json:"otp_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetRequest(ctx context.Context, arg CreatePasswordResetRequestParams) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, createPasswordResetRequest, arg.UserID, arg.OtpHash, arg.ExpiresAt)
	var i PasswordResetRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.ResetTokenHash,
		&i.ResetTokenExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetRequests = `-- name: DeleteExpiredPasswordResetRequests :execrows
DELETE FROM password_reset_requests
WHERE consumed_at IS NOT NULL
   OR (
        reset_token_expires_at IS NULL
        AND expires_at <= NOW()
   )
   OR reset_token_expires_at <= NOW()
`

// Optional cleanup query for a future worker.
func (q *Queries) DeleteExpiredPasswordResetRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasswordResetRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActivePasswordResetRequestForUpdate = `-- name: GetActivePasswordResetRequestForUpdate :one
SELECT
    id,
    user_id,
    otp_hash,
    attempts,
    expires_at,
    verified_at,
    reset_token_hash,
    reset_token_expires_at,
    consumed_at,
    created_at
FROM password_reset_requests
WHERE user_id = $1
  AND consumed_at IS NULL
  AND verified_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
FOR UPDATE
`

// Call this only after locking the user row.
// Returning expired or exhausted requests lets the service map every
// invalid state to one public error.
func (q *Queries) GetActivePasswordResetRequestForUpdate(ctx context.Context, userID int64) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, getActivePasswordResetRequestForUpdate, userID)
	var i PasswordResetRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.ResetTokenHash,
		&i.ResetTokenExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPasswordResetRequest = `-- name: GetLatestPasswordResetRequest :one
SELECT
    id,
    user_id,
    otp_hash,
    attempts,
    expires_at,
    verified_at,
    reset_token_hash,
    reset_token_expires_at,
    consumed_at,
    created_at
FROM password_reset_requests
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// Used to enforce the request cooldown.
func (q *Queries) GetLatestPasswordResetRequest(ctx context.Context, userID int64) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, getLatestPasswordResetRequest, userID)
	var i PasswordResetRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.ResetTokenHash,
		&i.ResetTokenExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetRequestByTokenHash = `-- name: GetPasswordResetRequestByTokenHash :one
SELECT
    id,
    user_id,
    otp_hash,
    attempts,
    expires_at,
    verified_at,
    reset_token_hash,
    reset_token_expires_at,
    consumed_at,
    created_at
FROM password_reset_requests
WHERE reset_token_hash = $1
`

// First lookup for confirmation. The service should then lock the user
// and reload this request with GetPasswordResetRequestForUpdate.
func (q *Queries) GetPasswordResetRequestByTokenHash(ctx context.Context, resetTokenHash []byte) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, getPasswordResetRequestByTokenHash, resetTokenHash)
	var i PasswordResetRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.ResetTokenHash,
		&i.ResetTokenExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetRequestForUpdate = `-- name: GetPasswordResetRequestForUpdate :one
SELECT
    id,
    user_id,
    otp_hash,
    attempts,
    expires_at,
    verified_at,
    reset_token_hash,
    reset_token_expires_at,
    consumed_at,
    created_at
FROM password_reset_requests
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPasswordResetRequestForUpdate(ctx context.Context, id int64) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, getPasswordResetRequestForUpdate, id)
	var i PasswordResetRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.ResetTokenHash,
		&i.ResetTokenExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPasswordResetAttempts = `-- name: IncrementPasswordResetAttempts :one
UPDATE password_reset_requests
SET attempts = attempts + 1
WHERE id = $1
  AND attempts < 5
  AND verified_at IS NULL
  AND consumed_at IS NULL
RETURNING attempts
`

func (q *Queries) IncrementPasswordResetAttempts(ctx context.Context, id int64) (int16, error) {
	row := q.db.QueryRow(ctx, incrementPasswordResetAttempts, id)
	var attempts int16
	err := row.Scan(&attempts)
	return attempts, err
}

const lockUserForPasswordResetByEmail = `-- name: LockUserForPasswordResetByEmail :one

SELECT
    id,
    email
FROM users
WHERE lower(email) = lower($1)
FOR UPDATE
`

type LockUserForPasswordResetByEmailRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

// Locking the user first gives request, verification, and confirmation
// transactions a consistent lock order.
func (q *Queries) LockUserForPasswordResetByEmail(ctx context.Context, email string) (LockUserForPasswordResetByEmailRow, error) {
	row := q.db.QueryRow(ctx, lockUserForPasswordResetByEmail, email)
	var i LockUserForPasswordResetByEmailRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const lockUserForPasswordResetByID = `-- name: LockUserForPasswordResetByID :one
SELECT
    id,
    email
FROM users
WHERE id = $1
FOR UPDATE
`

type LockUserForPasswordResetByIDRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) LockUserForPasswordResetByID(ctx context.Context, userID int64) (LockUserForPasswordResetByIDRow, error) {
	row := q.db.QueryRow(ctx, lockUserForPasswordResetByID, userID)
	var i LockUserForPasswordResetByIDRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const markPasswordResetVerified = `-- name: MarkPasswordResetVerified :one
UPDATE password_reset_requests
SET
    verified_at = $1,
    reset_token_hash = $2,
    reset_token_expires_at = $3
WHERE id = $4
  AND attempts < 5
  AND verified_at IS NULL
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING
    id,
    user_id,
    otp_hash,
    attempts,
    expires_at,
    verified_at,
    reset_token_hash,
    reset_token_expires_at,
    consumed_at,
    created_at
`

type MarkPasswordResetVerifiedParams struct {
	VerifiedAt          pgtype.Timestamptz `json:"verified_at"`
	ResetTokenHash      []byte             `json:"reset_token_hash"`
	ResetTokenExpiresAt pgtype.Timestamptz `json:"reset_token_expires_at"`
	ID                  int64              `json:"id"`
}

// Exchanges a correct OTP for a hashed opaque reset token.
func (q *Queries) MarkPasswordResetVerified(ctx context.Context, arg MarkPasswordResetVerifiedParams) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, markPasswordResetVerified,
		arg.VerifiedAt,
		arg.ResetTokenHash,
		arg.ResetTokenExpiresAt,
		arg.ID,
	)
	var i PasswordResetRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.ResetTokenHash,
		&i.ResetTokenExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPasswordAfterReset = `-- name: UpdateUserPasswordAfterReset :one
UPDATE users
SET
    password_hash = $1::text,
    updated_at = $2
WHERE id = $3
RETURNING id
`

type UpdateUserPasswordAfterResetParams struct {
	PasswordHash string             `json:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UserID       int64              `json:"user_id"`
}

func (q *Queries) UpdateUserPasswordAfterReset(ctx context.Context, arg UpdateUserPasswordAfterResetParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordAfterReset, arg.PasswordHash, arg.UpdatedAt, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
