// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_token.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    token_hash,
    expires_at
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    user_id,
    token_hash,
    expires_at,
    revoked_at,
    replaced_by_token_id,
    created_at
`

type CreateRefreshTokenParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT
    id,
    user_id,
    token_hash,
    expires_at,
    revoked_at,
    replaced_by_token_id,
    created_at
FROM refresh_tokens
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
		&i.CreatedAt,
	)
	return i, err
}

const markRefreshTokenReplaced = `-- name: MarkRefreshTokenReplaced :one
UPDATE refresh_tokens
SET
    revoked_at = NOW(),
    replaced_by_token_id = $1
WHERE id = $2
  AND revoked_at IS NULL
  AND replaced_by_token_id IS NULL
RETURNING
    id,
    user_id,
    token_hash,
    expires_at,
    revoked_at,
    replaced_by_token_id,
    created_at
`

type MarkRefreshTokenReplacedParams struct {
	ReplacedByTokenID pgtype.Int8 `json:"replaced_by_token_id"`
	ID                int64       `json:"id"`
}

func (q *Queries) MarkRefreshTokenReplaced(ctx context.Context, arg MarkRefreshTokenReplacedParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, markRefreshTokenReplaced, arg.ReplacedByTokenID, arg.ID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :execrows
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :execrows
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenByHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
