// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReviewForCompletedBooking = `-- name: CreateReviewForCompletedBooking :one
INSERT INTO reviews (
    booking_id,
    rating,
    comment
)
SELECT
    b.id,
    $1::smallint,
    $2::text
FROM bookings AS b
WHERE b.id = $3
  AND b.user_id = $4
  AND b.status = 'completed'
RETURNING
    id,
    booking_id,
    rating,
    comment,
    created_at,
    updated_at
`

type CreateReviewForCompletedBookingParams struct {
	Rating    int16       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
	BookingID int64       `json:"booking_id"`
	UserID    int64       `json:"user_id"`
}

func (q *Queries) CreateReviewForCompletedBooking(ctx context.Context, arg CreateReviewForCompletedBookingParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReviewForCompletedBooking,
		arg.Rating,
		arg.Comment,
		arg.BookingID,
		arg.UserID,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT
    r.id,
    r.rating,
    r.comment,
    r.created_at,
    r.updated_at,
    u.full_name AS reviewer_name,
    rt.name AS room_type_name,
    rt.hotel_id
FROM reviews AS r
JOIN bookings AS b
    ON b.id = r.booking_id
JOIN users AS u
    ON u.id = b.user_id
JOIN room_types AS rt
    ON rt.id = b.room_type_id
WHERE r.id = $1
`

type GetReviewByIDRow struct {
	ID           int64              `json:"id"`
	Rating       int16              `json:"rating"`
	Comment      pgtype.Text        `json:"comment"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ReviewerName string             `json:"reviewer_name"`
	RoomTypeName string             `json:"room_type_name"`
	HotelID      int64              `json:"hotel_id"`
}

func (q *Queries) GetReviewByID(ctx context.Context, reviewID int64) (GetReviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getReviewByID, reviewID)
	var i GetReviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewerName,
		&i.RoomTypeName,
		&i.HotelID,
	)
	return i, err
}

const listReviewsByHotel = `-- name: ListReviewsByHotel :many
SELECT
    r.id,
    r.rating,
    r.comment,
    r.created_at,
    r.updated_at,
    u.full_name AS reviewer_name,
    rt.name AS room_type_name
FROM reviews AS r
JOIN bookings AS b
    ON b.id = r.booking_id
JOIN users AS u
    ON u.id = b.user_id
JOIN room_types AS rt
    ON rt.id = b.room_type_id
WHERE rt.hotel_id = $1
ORDER BY r.created_at DESC, r.id DESC
`

type ListReviewsByHotelRow struct {
	ID           int64              `json:"id"`
	Rating       int16              `json:"rating"`
	Comment      pgtype.Text        `json:"comment"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ReviewerName string             `json:"reviewer_name"`
	RoomTypeName string             `json:"room_type_name"`
}

func (q *Queries) ListReviewsByHotel(ctx context.Context, hotelID int64) ([]ListReviewsByHotelRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByHotel, hotelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByHotelRow
	for rows.Next() {
		var i ListReviewsByHotelRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewerName,
			&i.RoomTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
