// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_types.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoomType = `-- name: CreateRoomType :one
INSERT INTO room_types (
    hotel_id,
    name,
    description,
    price_per_night,
    capacity,
    total_rooms
)
SELECT
    h.id,
    $1::text,
    $2::text,
    $3::numeric,
    $4::int,
    $5::int
FROM hotels AS h
WHERE h.id = $6
  AND h.is_active = true
RETURNING id, hotel_id, name, description, price_per_night, capacity, total_rooms, is_active, created_at
`

type CreateRoomTypeParams struct {
	Name          string         `json:"name"`
	Description   pgtype.Text    `json:"description"`
	PricePerNight pgtype.Numeric `json:"price_per_night"`
	Capacity      int32          `json:"capacity"`
	TotalRooms    int32          `json:"total_rooms"`
	HotelID       int64          `json:"hotel_id"`
}

func (q *Queries) CreateRoomType(ctx context.Context, arg CreateRoomTypeParams) (RoomType, error) {
	row := q.db.QueryRow(ctx, createRoomType,
		arg.Name,
		arg.Description,
		arg.PricePerNight,
		arg.Capacity,
		arg.TotalRooms,
		arg.HotelID,
	)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.HotelID,
		&i.Name,
		&i.Description,
		&i.PricePerNight,
		&i.Capacity,
		&i.TotalRooms,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateRoomType = `-- name: DeactivateRoomType :one
UPDATE room_types
SET is_active = false
WHERE id = $1
  AND is_active = true
RETURNING id
`

func (q *Queries) DeactivateRoomType(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deactivateRoomType, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getMaxRoomTypeInventoryUsage = `-- name: GetMaxRoomTypeInventoryUsage :one
SELECT COALESCE(MAX(rooms_booked + rooms_blocked), 0)::int
FROM room_type_availability
WHERE room_type_id = $1
`

func (q *Queries) GetMaxRoomTypeInventoryUsage(ctx context.Context, roomTypeID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxRoomTypeInventoryUsage, roomTypeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getRoomTypeByID = `-- name: GetRoomTypeByID :one
SELECT rt.id, rt.hotel_id, rt.name, rt.description, rt.price_per_night, rt.capacity, rt.total_rooms, rt.is_active, rt.created_at
FROM room_types AS rt
JOIN hotels AS h
    ON h.id = rt.hotel_id
WHERE rt.id = $1
  AND rt.is_active = true
  AND h.is_active = true
`

func (q *Queries) GetRoomTypeByID(ctx context.Context, id int64) (RoomType, error) {
	row := q.db.QueryRow(ctx, getRoomTypeByID, id)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.HotelID,
		&i.Name,
		&i.Description,
		&i.PricePerNight,
		&i.Capacity,
		&i.TotalRooms,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomTypeForUpdate = `-- name: GetRoomTypeForUpdate :one
SELECT rt.id, rt.hotel_id, rt.name, rt.description, rt.price_per_night, rt.capacity, rt.total_rooms, rt.is_active, rt.created_at
FROM room_types AS rt
JOIN hotels AS h
    ON h.id = rt.hotel_id
WHERE rt.id = $1
  AND rt.is_active = true
  AND h.is_active = true
FOR SHARE OF h
FOR UPDATE OF rt
`

func (q *Queries) GetRoomTypeForUpdate(ctx context.Context, id int64) (RoomType, error) {
	row := q.db.QueryRow(ctx, getRoomTypeForUpdate, id)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.HotelID,
		&i.Name,
		&i.Description,
		&i.PricePerNight,
		&i.Capacity,
		&i.TotalRooms,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAvailableRoomTypes = `-- name: ListAvailableRoomTypes :many
SELECT
    rt.id,
    rt.hotel_id,
    rt.name,
    rt.description,
    rt.price_per_night,
    rt.capacity,
    rt.total_rooms,
    rt.created_at,
    (
         rt.total_rooms
    - COALESCE(MAX(rta.rooms_booked + rta.rooms_blocked), 0)
    )::int AS rooms_available
FROM room_types AS rt
JOIN hotels AS h
    ON h.id = rt.hotel_id
LEFT JOIN room_type_availability AS rta
    ON rta.room_type_id = rt.id
   AND rta.date >= $1::date
   AND rta.date < $2::date
WHERE rt.hotel_id = $3
  AND rt.is_active = true
  AND  h.is_active = true
GROUP BY rt.id
HAVING
    rt.total_rooms
        - COALESCE(MAX(rta.rooms_booked + rta.rooms_blocked), 0)
        >= $4::int
    AND rt.capacity * $4::int
        >= $5::int
ORDER BY rt.price_per_night, rt.id
`

type ListAvailableRoomTypesParams struct {
	CheckIn    pgtype.Date `json:"check_in"`
	CheckOut   pgtype.Date `json:"check_out"`
	HotelID    int64       `json:"hotel_id"`
	RoomsCount int32       `json:"rooms_count"`
	GuestCount int32       `json:"guest_count"`
}

type ListAvailableRoomTypesRow struct {
	ID             int64              `json:"id"`
	HotelID        int64              `json:"hotel_id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	PricePerNight  pgtype.Numeric     `json:"price_per_night"`
	Capacity       int32              `json:"capacity"`
	TotalRooms     int32              `json:"total_rooms"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RoomsAvailable int32              `json:"rooms_available"`
}

func (q *Queries) ListAvailableRoomTypes(ctx context.Context, arg ListAvailableRoomTypesParams) ([]ListAvailableRoomTypesRow, error) {
	rows, err := q.db.Query(ctx, listAvailableRoomTypes,
		arg.CheckIn,
		arg.CheckOut,
		arg.HotelID,
		arg.RoomsCount,
		arg.GuestCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableRoomTypesRow
	for rows.Next() {
		var i ListAvailableRoomTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.HotelID,
			&i.Name,
			&i.Description,
			&i.PricePerNight,
			&i.Capacity,
			&i.TotalRooms,
			&i.CreatedAt,
			&i.RoomsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomTypesByHotel = `-- name: ListRoomTypesByHotel :many
SELECT rt.id, rt.hotel_id, rt.name, rt.description, rt.price_per_night, rt.capacity, rt.total_rooms, rt.is_active, rt.created_at
FROM room_types AS rt
JOIN hotels AS h
    ON h.id = rt.hotel_id
WHERE rt.hotel_id = $1
  AND rt.is_active = true
  AND h.is_active = true
ORDER BY rt.price_per_night, rt.id
`

func (q *Queries) ListRoomTypesByHotel(ctx context.Context, hotelID int64) ([]RoomType, error) {
	rows, err := q.db.Query(ctx, listRoomTypesByHotel, hotelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomType
	for rows.Next() {
		var i RoomType
		if err := rows.Scan(
			&i.ID,
			&i.HotelID,
			&i.Name,
			&i.Description,
			&i.PricePerNight,
			&i.Capacity,
			&i.TotalRooms,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomType = `-- name: UpdateRoomType :one
UPDATE room_types
SET
    name = $2,
    description = $3,
    price_per_night = $4,
    capacity = $5,
    total_rooms = $6
WHERE id = $1
RETURNING id, hotel_id, name, description, price_per_night, capacity, total_rooms, is_active, created_at
`

type UpdateRoomTypeParams struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Description   pgtype.Text    `json:"description"`
	PricePerNight pgtype.Numeric `json:"price_per_night"`
	Capacity      int32          `json:"capacity"`
	TotalRooms    int32          `json:"total_rooms"`
}

func (q *Queries) UpdateRoomType(ctx context.Context, arg UpdateRoomTypeParams) (RoomType, error) {
	row := q.db.QueryRow(ctx, updateRoomType,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PricePerNight,
		arg.Capacity,
		arg.TotalRooms,
	)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.HotelID,
		&i.Name,
		&i.Description,
		&i.PricePerNight,
		&i.Capacity,
		&i.TotalRooms,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
