// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, full_name, phone, role, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	Phone     pgtype.Text        `json:"phone"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = $2,
    full_name = $3,
    phone = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, email, full_name, phone, role, created_at, updated_at
`

type UpdateUserParams struct {
	ID       int64       `json:"id"`
	Email    string      `json:"email"`
	FullName string      `json:"full_name"`
	Phone    pgtype.Text `json:"phone"`
}

type UpdateUserRow struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	Phone     pgtype.Text        `json:"phone"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.Phone,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
